# Generated by Django 4.2 on 2023-08-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, verbose_name='İsmi')),
                ('movie_description', models.TextField(max_length=400, verbose_name='Açıklama')),
                ('movie_image', models.FileField(upload_to='Uploads', verbose_name='Banner')),
                ('movie_likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Tip')),
            ],
        ),
        migrations.CreateModel(
            name='NetflixProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hesap Adı')),
                ('avatar', models.FileField(default='/image/avatar.png', upload_to='Avatars', verbose_name='Fotoğraf')),
            ],
        ),
        migrations.RemoveField(
            model_name='netflixuser',
            name='avatar',
        ),
        migrations.CreateModel(
            name='NetflixProfileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_user_app.movies', verbose_name='Film')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_user_app.netflixprofile', verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='netflixprofile',
            name='list',
            field=models.ManyToManyField(to='netflix_user_app.netflixprofilelist', verbose_name='Liste'),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_user_app.movietypes', verbose_name='Türü'),
        ),
        migrations.AddField(
            model_name='netflixuser',
            name='profile',
            field=models.ManyToManyField(to='netflix_user_app.netflixprofile', verbose_name='Alt Hesap'),
        ),
    ]
