# Generated by Django 4.2 on 2023-08-21 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0002_movies_movietypes_netflixprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netflixprofile',
            name='main_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ana Hesap'),
        ),
    ]
