# Generated by Django 4.2 on 2023-08-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0003_netflixprofile_main_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixprofile',
            name='avatar',
            field=models.FileField(blank=True, default='/image/avatar.png', upload_to='Avatars', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='netflixprofile',
            name='list',
            field=models.ManyToManyField(blank=True, to='netflix_user_app.netflixprofilelist', verbose_name='Liste'),
        ),
    ]
