# Generated by Django 4.2 on 2023-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0005_alter_netflixprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=50, verbose_name='Alt Kategori Adı')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_categories',
            field=models.ManyToManyField(to='netflix_user_app.moviecategories', verbose_name='Etiketler'),
        ),
    ]
