# Generated by Django 4.2 on 2023-08-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0006_moviecategories_movies_movie_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_source',
            field=models.URLField(blank=True, verbose_name='Kaynak'),
        ),
    ]
