# Generated by Django 4.2 on 2023-08-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0007_movies_movie_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_source',
            field=models.URLField(blank=True, help_text="Filmin URL'i", verbose_name='Kaynak'),
        ),
    ]
