# Generated by Django 4.2 on 2023-08-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0008_alter_movies_movie_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netflixprofilelist',
            name='profile',
        ),
    ]
