# Generated by Django 4.2 on 2023-08-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0009_remove_netflixprofilelist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixprofile',
            name='list',
            field=models.ManyToManyField(blank=True, to='netflix_user_app.movies', verbose_name='Liste'),
        ),
        migrations.DeleteModel(
            name='NetflixProfileList',
        ),
    ]
