# Generated by Django 4.2 on 2023-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0011_remove_movies_movie_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_source',
            field=models.FileField(blank=True, upload_to='Videos', verbose_name='Kaynağı'),
        ),
    ]
