# Generated by Django 4.2 on 2023-09-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0012_movies_movie_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='netflixuser',
            name='tel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon Numarası'),
        ),
    ]
