# Generated by Django 4.2 on 2023-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0013_netflixuser_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='netflixuser',
            name='isPremium',
            field=models.BooleanField(default=False, verbose_name='Üye mi'),
        ),
    ]
