# Generated by Django 4.2 on 2023-09-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0014_netflixuser_ispremium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixuser',
            name='isPremium',
            field=models.BooleanField(default=False, help_text='İşaretliyse kullanıcı film/dizi izleyebilir', verbose_name='Üye mi'),
        ),
    ]
