# Generated by Django 4.2 on 2023-09-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0015_alter_netflixuser_ispremium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kart üzerindeki ad ve soyad')),
                ('no', models.CharField(max_length=15, verbose_name='Kart Numarası')),
                ('cvc', models.CharField(max_length=3, verbose_name='Güvenlik Numarası')),
                ('valid', models.CharField(max_length=4, verbose_name='Son Kullanma')),
            ],
        ),
        migrations.AddField(
            model_name='netflixuser',
            name='debitCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix_user_app.card', verbose_name='Kart'),
        ),
    ]
