# Generated by Django 4.2 on 2023-09-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_user_app', '0016_card_netflixuser_debitcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='adress',
            field=models.CharField(blank=True, max_length=50, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='card',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='card',
            name='zip',
            field=models.IntegerField(default=0, verbose_name='Zip Kodu'),
        ),
    ]
