# Generated by Django 4.2 on 2023-09-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Adı')),
                ('lastname', models.CharField(max_length=50, verbose_name='SoyAdı')),
                ('salary', models.IntegerField(default=0, verbose_name='Maaş')),
                ('role', models.CharField(max_length=50, verbose_name='Rolü')),
            ],
        ),
    ]
