# Generated by Django 4.1.1 on 2023-05-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='İçerik Türü')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('movie_description', models.TextField(verbose_name='Açıklama')),
                ('movie_cover', models.FileField(upload_to='Uploads', verbose_name='Afiş')),
                ('movie_category', models.ManyToManyField(to='userApp.categories', verbose_name='Tags')),
                ('movie_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.type', verbose_name='İçerik Tipi')),
            ],
        ),
    ]
