# Generated by Django 4.1.1 on 2023-05-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Options',
        ),
    ]
