# Generated by Django 4.1.1 on 2023-05-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_delete_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_cover',
            field=models.FileField(blank=True, null=True, upload_to='Uploads', verbose_name='Afiş'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_type',
            field=models.ForeignKey(help_text='Film/Dizi içerik türü', on_delete=django.db.models.deletion.CASCADE, to='userApp.type', verbose_name='İçerik Tipi'),
        ),
    ]
