# Generated by Django 4.2 on 2023-05-15 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_alter_movies_movie_cover_alter_movies_movie_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ManyToManyField(to='userApp.movies', verbose_name='Favori Listesi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ana Hesabı')),
            ],
        ),
        migrations.AddField(
            model_name='netflixuser',
            name='profile',
            field=models.ManyToManyField(to='userApp.netflixprofile', verbose_name='Userin Alt Hesapları'),
        ),
    ]
