# Generated by Django 4.2 on 2023-05-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_remove_netflixuser_avatar_netflixprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixprofile',
            name='avatar',
            field=models.FileField(blank=True, default='', null=True, upload_to='Avatar', verbose_name='User Avatar'),
        ),
    ]
