# Generated by Django 4.2 on 2023-05-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0010_netflixprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Profil İlk Adı'),
        ),
    ]
