# Generated by Django 4.2 on 2023-05-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0011_alter_netflixprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixprofile',
            name='movie',
            field=models.ManyToManyField(to='userApp.movies', verbose_name='Favori Listesi'),
        ),
    ]
