# Generated by Django 4.2 on 2023-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0012_alter_netflixprofile_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netflixprofile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='netflixprofile',
            name='movie',
            field=models.ManyToManyField(default=1, to='userApp.movies', verbose_name='Favori Listesi'),
        ),
    ]
