# Generated by Django 4.1.1 on 2023-05-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Kategori İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_type', models.CharField(max_length=50, verbose_name='İçerik Türü')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, verbose_name='Film Adı')),
                ('movie_description', models.TextField(max_length=250, verbose_name='Film Açıklaması')),
                ('movie_avatar', models.FileField(upload_to='Uploads', verbose_name='Banner')),
                ('movie_createdAt', models.TimeField(auto_now=True, verbose_name='Eklenme Tarihi')),
                ('movie_liked', models.PositiveIntegerField(default=0, verbose_name='Beğeni Sayısı')),
                ('movie_disliked', models.PositiveIntegerField(default=0, verbose_name='Beğenilmeme Sayısı')),
                ('movie_category', models.ManyToManyField(to='userApp.category', verbose_name='Kategorisi')),
                ('movie_type', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='userApp.type', verbose_name='Tür')),
            ],
        ),
        migrations.AddField(
            model_name='newuser',
            name='movie_list',
            field=models.ManyToManyField(to='userApp.movie', verbose_name='Favori Listesi'),
        ),
    ]
