# Generated by Django 4.1.1 on 2023-05-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_category_type_movie_newuser_movie_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_type',
        ),
    ]
