# Generated by Django 4.1.1 on 2023-05-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_remove_movie_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userApp.type', verbose_name='İçerik Türü'),
        ),
    ]
