# Generated by Django 4.1.1 on 2023-05-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_movie_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.ForeignKey(default='Dizi', on_delete=django.db.models.deletion.CASCADE, to='userApp.type', verbose_name='İçerik Türü'),
        ),
    ]
