# Generated by Django 4.1.1 on 2023-05-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_alter_movie_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='Avatar', verbose_name='Avatar'),
        ),
    ]
